import { Suspense } from "react";
import type { Metadata } from "next";
import clsx from "clsx";
import { Comfortaa, Rubik } from "next/font/google";
import "./globals.css";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontEn = Rubik({
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
});
const fontRu = Comfortaa({
  subsets: ["cyrillic", "cyrillic-ext"],
  weight: ["700"],
});

export default async function RootLayout({
  children, // & params
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { X } = await params
  return (
    <html lang="en">
      <head></head>
      <body className={clsx("antialiased", fontEn.className, fontRu.className)}>
        <Suspense fallback={<Loading />}>
          <div>{children}</div>
        </Suspense>
      </body>
    </html>
  );
}
