import { Suspense } from "react";
import type { Metadata } from "next";
import clsx from "clsx";
import { Comfortaa, Rubik } from "next/font/google";
import "./globals.css";
import Loading from "./loading";
import { SideMenu } from "@/widgets/SideMenu";
import { TopHeader } from "@/widgets/TopHeader";
import { UnderFooter } from "@/widgets/UnderFooter";
// import { AppProvider } from "@/widgets/AppProvider";
import { QueryProvider } from "@/shared/lib/providers/QueryProvider";
import { useAuth } from "@/shared/lib/hooks/useAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontEn = Rubik({
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
});
const fontRu = Comfortaa({
  subsets: ["cyrillic", "cyrillic-ext"],
  weight: ["700"],
});

export default function RootLayout({
  children, // & params
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { X } = await params
  useAuth();

  return (
    <html lang="en" className="dark">
      <head></head>

      <body className={clsx("antialiased", fontEn.className, fontRu.className)}>
        <div className="flex">
          <SideMenu />
          <div className="flex-1">
            <QueryProvider>
              <TopHeader />
              <Suspense fallback={<Loading />}>{children}</Suspense>
              <UnderFooter />
            </QueryProvider>
          </div>
        </div>
        <div id="portal-root" />
      </body>
    </html>
  );
}
